### ISSUE TITLE
Incompatibility with Mojang authlib

### ISSUE THREAD

**Issue by Rocologo** [GlowstoneMC/Glowstone#813]
I am trying to make my plugin MobHunting work with Glowstone and tested it on V2018.0.0 today

My plugin failed with this:

```
12:59:24 [SEVERE] Error occurred while enabling MobHunting v5.4.3-SNAPSHOT-BTestBuild (Is it up to date?)
java.lang.NoClassDefFoundError: com/mojang/authlib/GameProfile
	at one.lindegaard.MobHunting.rewards.CustomItems.getCustomtexture(CustomItems.java:269)
	at one.lindegaard.MobHunting.mobs.MinecraftMob.getCustomHead(MinecraftMob.java:884)
	at one.lindegaard.MobHunting.mobs.ExtendedMob.getCustomHead(ExtendedMob.java:168)
	at one.lindegaard.MobHunting.achievements.BasicHuntAchievement.getSymbol(BasicHuntAchievement.java:76)
	at io.chazza.advancementapi.AdvancementManager.getAdvancementsFromAchivements(AdvancementManager.java:62)
	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:317)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:1061)
	at net.glowstone.GlowServer.start(GlowServer.java:727)
	at net.glowstone.GlowServer.run(GlowServer.java:559)
	at net.glowstone.GlowServer.main(GlowServer.java:426)
Caused by: java.lang.ClassNotFoundException: com.mojang.authlib.GameProfile
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

```
Is there anyway make this work, it seems that GameProfile is not supported?

**Comment by Paulomart** [comment]
Glowstone is reimplementing the hole Bukkit API, therefore there is no `com.mojang.*`, `net.minecraft.*` and `org.bukkit.craftbukkit.*` classes. However there is a own implemention of the GameProfile: https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/entity/meta/profile/PlayerProfile.java

**Comment by aramperes** [comment]
Although Paper added a Profile API depending on Mojang's authlib a while back, we removed this dependency and reverted the additions because it uses Vanilla internals. We made a suggestion to Paper to remove this dependency and make an abstract API, for platform-independence-sake. [More info here](https://github.com/PaperMC/Paper/issues/828).

As of writing, the Paper team is currently working on abstracting their API. [The first PR is here](https://github.com/PaperMC/Paper/pull/974). The current API which uses `GameProfile` is currently deprecated and will be removed before 1.13 is released.

I'll keep this issue open until Paper finishes their API migration and we implement it.

In the mean time, you can use the `PlayerProfile` class like @Paulomart suggested.

**Comment by Rocologo** [comment]
Ok, thanks i will see if am able to use PlayerProfile

**Comment by mastercoms** [comment]
API has been added to Paper in https://github.com/PaperMC/Paper/commit/71c18fd5c9e3520fd8ebc3029be7a56487c77475 and https://github.com/PaperMC/Paper/commit/5b72a03bcf0f5f3d31cd6fe393b883dbbcd5e1fa. We are working on the implementation for this now.

**Comment by aramperes** [comment]
Done in #817, please update your plugin to the latest Paper API version.

Note that Glowstone's profile implementation, previously `PlayerProfile`, was moved to `GlowPlayerProfile`. Although you should use the `PlayerProfile` interface which is part of Paper API.
